parameters:
    database_driver:   pdo_sqlite
    database_host:     127.0.0.1
    database_port:     null
    database_name:     humanreborn
    database_user:     root
    database_password: eipbilantech

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            EIPHUm4R3B0rnS0S3cRetT0k3N
    register:          false
