<?php

namespace EIP\HRBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HRClanRankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HRClanRankRepository extends EntityRepository
{
    public function getAllRankFromClan($idClan){
        
        $qb = $this->getEntityManager()->createQueryBuilder()
                ->select('r.id as id, r.idClan as idClan, r.name as name, r.CanFireMember as cfire,
                          r.CanAcceptNewMember as chire, r.CanEditText as cedit, r.CanDeclareWar as cwars,
                          r.CanCreateRank as crank, r.canDeleteClan as cdele')
                ->from("EIPHRBundle:HRClanRank", "r")
                ->leftJoin("EIPHRBundle:HRClan", "c", "WITH", "c.id = r.idClan")
                ->where("r.idClan = :idClan")
                ->groupBy("r.id")->setParameter(':idClan', $idClan);

        $res = $qb->getQuery()->getResult();
        
        return $res;
         
    }
    
    public function getRankLines($idClan) {
        $qb = $this->getEntityManager()->createQueryBuilder()
                ->select('r')
                ->from("EIPHRBundle:HRClanRank", "r")
                ->where("r.idClan = :idClan")
                ->setParameter(':idClan', $idClan);

        $res = $qb->getQuery()->getResult();
        
        return $res;
    }
    
    public function isThisRankExist($rank, $idClan) {
        $qb = $this->getEntityManager()->createQuery(
                "SELECT r FROM EIPHRBundle:HRClanRank as r WHERE r.name = :nrank AND r.idClan = :idclan")
                ->setParameter(':nrank', $rank)->setParameter(':idclan', $idClan);
        $res = $qb->getResult();
        if (empty($res))
            return false;
        return true;
    }
    
    public function getRankFromId($idRank) {
        $qb = $this->getEntityManager()->createQueryBuilder()
                ->select('r')
                ->from('EIPHRBundle:HRClanRank', 'r')
                ->where('r.id = :idrank')->setParameter(":idrank", $idRank);
        return $qb->getQuery()->getResult();
    }
    
    public function getRankName($idRank) {
        $qb = $this->getEntityManager()->createQueryBuilder()
                ->select('r.name as name')
                ->from('EIPHRBundle:HRClanRank', 'r')
                ->where('r.id = :idrank')->setParameter(":idrank", $idRank);
        $rankName = $qb->getQuery()->getResult();
        if ($rankName)
            return $rankName[0];
        else
            return null;
    }

}
